FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o test-client ./test/manual

FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/test-client .

ENTRYPOINT ["/app/test-client"]
